### PR TITLE
Update Drivetrain.java

### PR DESCRIPTION
**Pull request by HenryWeinman**

### CODE REVIEW

**Comment by henryscheible** [comment]
Looks good, just one thing you should fix. Currently, you have the sendDriveSignal function defined with parameters double right, double left, while conventionally you should use double left, double right. This isn't absolutely required, its just how others will expect to use the function so you should change it.

**Comment by henryscheible** [comment]
When you make a change, make sure you push to this DrivetrainV2 branch, not a new branch and not master

**Comment by HenryWeinman** [comment]
Ok, I think I did it.

**Review by henryscheible — APPROVED** [review]
Looks Great, I added the ctre libraries

**Comment by HenryWeinman** [comment]
Awesome, Thanks. So thats it?

**Pull request merged**
